### ISSUE TITLE
Service appears to be erroring

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/maitland#1]
```
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!' : 500 Internal Server Error (RestClient::InternalServerError)
    from /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
    from /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    from /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    from /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    from /app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
    from /app/vendor/bundle/ruby/2.0.0/gems/atdis-0.3.13/lib/atdis/model.rb:73:in `read_url'
    from /app/vendor/bundle/ruby/2.0.0/gems/atdis-0.3.13/lib/atdis/feed.rb:62:in `applications'
    from /app/vendor/bundle/ruby/2.0.0/bundler/gems/atdisplanningalertsfeed-d3fb8a71db27/lib/atdisplanningalertsfeed.rb:11:in `save'
    from scraper.rb:6:in `<main>'
```

**Comment by henare** [comment]
Strange. Visiting it in my browser works https://myhorizon.maitland.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json

**Comment by CloCkWeRX** [comment]
May have gotten it in a maintenance window

**Comment by henare** [comment]
I just tried manually running the scraper and got the same error :crying_cat_face:

**Comment by CloCkWeRX** [comment]
https://myhorizon.maitland.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json?lodgement_date_start=2016-03-01&lodgement_date_end=2016-04-01

```
HTTP Status 500 - com.bas.connectionserver.server.D: Value of suburb must be provided
```

**Comment by CloCkWeRX** [comment]
Sent (to Solorient):

```
Hi Christopher,
Sorry to keep bugging you like this!

Another mapping bug in https://myhorizon.maitland.nsw.gov.au/Horizon/@@horizondap@@/atdis/1.0/applications.json?lodgement_date_start=2016-03-01&lodgement_date_end=2016-04-01

has cropped up.

com.bas.connectionserver.server.D: Value of suburb must be provided
    com.bas.connectionserver.server.ConnectionFactory.A(Unknown Source)
    com.bas.connectionserver.server.ConnectionFactory.sendMessage(Unknown Source)
    com.bas.webapp.common.WebAppUtils.sendMessageToExecutionEngine(Unknown Source)
    com.bas.webapp.common.WebAppUtils.sendMessageToExecutionEngine(Unknown Source)
    com.bas.webapp.thin.servlets.RESTServlet.A(Unknown Source)
    com.bas.webapp.thin.servlets.RESTServlet.A(Unknown Source)
    com.bas.webapp.thin.servlets.RESTServlet.doGet(Unknown Source)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

I figure that from time to time issues like this will pop up; is there a more generic support email you'd prefer this sort of thing to go to?

In other news, we're just about to put a number of the feeds we're consuming into production planningalerts.org.au - you should see a few horizon installs listed on https://www.planningalerts.org.au/authorities :)
```

**Comment by CloCkWeRX** [comment]
Reply:

```
The Maitland problem is caused from data provided.  One application doesn’t have a property assigned yet.  I have updated the process will will be applied after tonights sync from their legacy system.
```
